server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.132.201.94:3306/editjs?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 180000
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
edit:
  enabled: false
  base-url: editjs
  cli-dir: /Users/admin/code-workspace/cli-dir
act-modeler: true
logging:
  level:
    com.edit.dddweb: debug